version: 1

# "merge" defines how to merge PRs into the target
merge:

  # "whitelist" defines how to select PRs to evaluate and merge
  whitelist:

    # "labels" is a list of labels that must be matched to whitelist a PR for merging (case-insensitive)
    labels: ["auto_merge"]

  # "blacklist" defines how to exclude PRs from evaluation and merging
  blacklist:

    # similar as above, "labels" defines a list of labels. In this case, matched labels cause exclusion. (case-insensitive)
    labels: ["no_auto_merge"]

  # "method" defines how to merge in changes. Available options are "merge", "rebase" and "squash"
  method: rebase

  # "delete_after_merge" is a bool that will cause merged PRs to be deleted once they are successfully merged
  delete_after_merge: true

# "update" defines how to keep open PRs up to date
update:

  method: rebase

  # The "whitelist" and "blacklist" options here operate the same as described for the `merge` block.
  whitelist:
    labels: ["auto_merge"]

